### ISSUE TITLE
Linage -> Source description deleted permanently

### ISSUE THREAD

**Issue by spatialgeorge** [geonetwork-delwp/core-geonetwork#27]
I can add new text in the Linage -->Source description but when deleted I don't have the option to add it again.

Also if there is already text in the Source-description and its deleted, cannot add that tab again.

![image](https://user-images.githubusercontent.com/46309965/168690788-3a9b1e77-ca07-427c-80a7-5e770c3798c0.png)
 Source description but when deleted I don't have the option to add it again.

**Comment by sppigot** [comment]
George - the problem here is that source and process step are displaying in boxed fields. That's ok for process step because you can only remove the "Process step" box that contains the Description but "Source" allows you to delete the Description leaving an empty Source box. You can recover by deleting the Source box but it's a bit clunky. Solution is to display the fields differently and don't let them be boxed.

**Comment by sppigot** [comment]
Done - note this is the wrong repo to record issues against - it's the core-geonetwork repo in https://github.com/delwp-gn/core-geonetwork.git

**Comment by tp0b** [comment]
testing on 22/6/2022 on GN DEV, it is working
https://dev-metashare.maps.vic.gov.au/geonetwork/srv/eng/catalog.edit#/metadata/18239?redirectUrl=catalog.search%23%2Fmetadata%2F226ada5a-8fb1-449a-8d1e-d3072f5b22c2&tab=resourceLineage

![image](https://user-images.githubusercontent.com/64397239/174913539-0f90a596-269f-4360-b7db-01702cb550c7.png)
